### ISSUE TITLE
来自后端的Legacy颜色符号无法直接着色为MiniMessage

### ISSUE THREAD

**Issue by HackHsda** [CatMoe/MoeFilter#43]
如题 安装了MoeFiler后 过了frist join检测 使用AjQueue的命令/queue Lobbys 进入的第一秒被提出并且玩家显示disconnected
如果要视频请加我的qq3218153361

**Comment by FallenCrystal** [comment]
您正在使用哪个版本的MoeFilter?

**Comment by FallenCrystal** [comment]
有插件在对BungeeCord执行网络操纵时出现错误 这应该不是MoeFilter的问题 如果您需要更多信息 请在config.conf中打开debug模式

祝您有美好的一天

此问题将在未回应3天后关闭

**Comment by HackHsda** [comment]
最新版本 开启Debug后有一个报错
```
[08:25:37 ERROR]: net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a
 MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more informat
ion.
[08:25:37 ERROR]:       <light_purple>MoeFilter <aqua><- <green>Plugin-Hide-Pro
[08:25:37 ERROR]:                                               ^^
[08:25:37 ERROR]:       at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170)
[08:25:37 ERROR]:       at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112)
[08:25:37 ERROR]:       at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195)
[08:25:37 ERROR]:       at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209)
[08:25:37 ERROR]:       at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:79)
[08:25:37 ERROR]:       at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:45)
[08:25:37 ERROR]:       at catmoe.fallencrystal.moefilter.util.message.component.ComponentUtil.parse(ComponentUtil.kt:39)
[08:25:37 ERROR]:       at catmoe.fallencrystal.moefilter.util.message.v2.MessageUtil.colorize(MessageUtil.kt:100)
[08:25:37 ERROR]:       at catmoe.fallencrystal.moefilter.network.bungee.handler.PacketHandler.write(PacketHandler.kt:63)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[08:25:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[08:25:37 ERROR]:       at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
[08:25:37 ERROR]:       at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153)
[08:25:37 ERROR]:       at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:323)
[08:25:37 ERROR]:       at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93)
[08:25:37 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[08:25:37 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[08:25:37 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[08:25:37 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[08:25:37 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[08:25:37 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[08:25:37 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[08:25:37 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[08:25:37 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[08:25:37 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[08:25:37 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[08:25:37 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08:25:37 ERROR]:       at java.lang.Thread.run(Thread.java:750)
[08:25:37 INFO]: [MoeFilter] [AntiBot] /120.243.101.159 are temp firewalled (30 seconds)
[08:25:37 ERROR]: java.lang.Throwable
[08:25:37 ERROR]:       at catmoe.fallencrystal.moefilter.common.firewall.Firewall.logFirewalled(Firewall.kt:70)
[08:25:37 ERROR]:       at catmoe.fallencrystal.moefilter.common.firewall.Firewall.addAddressTemp(Firewall.kt:57)
[08:25:37 ERROR]:       at catmoe.fallencrystal.moefilter.network.common.ExceptionCatcher.handle(ExceptionCatcher.kt:51)
[08:25:37 ERROR]:       at catmoe.fallencrystal.moefilter.network.bungee.handler.PacketHandler.exceptionCaught(PacketHandler.kt:40)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
[08:25:37 ERROR]:       at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92)
[08:25:37 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeEncodeHandler.exceptionCaught(BungeeEncodeHandler.java:108)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
[08:25:37 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143)
[08:25:37 ERROR]:       at com.viaversion.viaversion.bungee.handlers.BungeeDecodeHandler.exceptionCaught(BungeeDecodeHandler.java:61)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317)
[08:25:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325)
[08:25:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
[08:25:37 ERROR]:       at io.netty.channel.VoidChannelPromise.fireException0(VoidChannelPromise.java:236)
[08:25:37 ERROR]:       at io.netty.channel.VoidChannelPromise.tryFailure(VoidChannelPromise.java:178)
[08:25:37 ERROR]:       at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.notifyOutboundHandlerException(AbstractChannelHandlerContext.java:
990)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:884)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
[08:25:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
[08:25:37 ERROR]:       at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
[08:25:37 ERROR]:       at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153)
[08:25:37 ERROR]:       at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:323)
[08:25:37 ERROR]:       at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93)
[08:25:37 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[08:25:37 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[08:25:37 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[08:25:37 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[08:25:37 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[08:25:37 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
[08:25:37 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
[08:25:37 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[08:25:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[08:25:37 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[08:25:37 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[08:25:37 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[08:25:37 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[08:25:37 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[08:25:37 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[08:25:37 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[08:25:37 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[08:25:37 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[08:25:37 ERROR]:       at java.lang.Thread.run(Thread.java:750)
```

**Comment by FallenCrystal** [comment]
MoeFilter的brand仅支持MiniMessage格式, Pl-Hide-Pro所提供的legacy颜色是不允许被MiniMessage解析的
尝试在MoeFilter配置文件中修改brand 修改后端的brand或~~彻底禁用该功能~~ (将在之后的版本发行此功能)

**Comment by FallenCrystal** [comment]
尝试验证 https://github.com/CatMoe/MoeFilter/commit/b03d17fbf0051746e515f27d904ded973beb4a0e 提交的版本是否已经解决了您所遇到的问题. 目前后端服务端标识将会被自动转换为MiniMessage的Component.

如果您不想/不会构建 这里有已经构建的工件: [MoeFilter.zip](https://github.com/CatMoe/MoeFilter/files/12297112/MoeFilter.zip)

> 如果您遇到了配置文件的问题 请尝试重置配置文件 或修改以下栏目:

旧:
```
f3-brand="<light_purple>MoeFilter <aqua><- <green>%backend%"
```

新:

```
# f3服务端标识. 在较高版本的客户端上按F3即可看到.
# gradient和其它标签e.x <newline> 不可在此处使用
# 占位符: %bungee%: BungeeCord名称, %version%: BungeeCord版本, %backend%: 后端服务器名称
f3-brand {
    enabled=true
    custom="<light_purple>MoeFilter <aqua><- <green>%backend%"
}
```

**Comment by FallenCrystal** [comment]
此问题被标记为已解决 如果您仍然遇到此问题 请在下面发表comment并补充您所遇到的问题
