### ISSUE TITLE
BaseComponent is mandatory for BungeeCord 0f5f09b and later

### ISSUE THREAD

**Issue by shaqupl** [CatMoe/MoeFilter#75]
![image](https://github.com/CatMoe/MoeFilter/assets/68109218/0e5c224a-fe2f-420c-977f-f47e58e5f364)

**Comment by FallenCrystal** [comment]
this plugin is a bungeecord (proxy) plugin. u must first configure a bungeecord proxy and then place it in the plugins folder on the bungeecord proxy server.

**Comment by shaqupl** [comment]
Can you anserw in english pls, because the translator messed up the sentence. @FallenCrystal

**Comment by FallenCrystal** [comment]
> Can you anserw in english pls, because the translator messed up the sentence. @FallenCrystal

sry idk which language ur using. i will try to communicate with u using eng.

> however, most of the config files in this plugin are declared in chinese. so u might have a little trouble configuring it. if u have difficulty configuring. i might recommend u to use another plugin. e.g. Sonar (found in the credits list in the readme)

**Comment by shaqupl** [comment]
Is this a plugin or module? Can I use it with Waterfall?

**Comment by FallenCrystal** [comment]
> Is this a plugin or module? Can I use it with Waterfall?

plugin. put it in waterfall plugin folder.

**Comment by shaqupl** [comment]
I, did. Console looks pretty dirty. Check out the logs

**Comment by shaqupl** [comment]
```
[15:15:13] [main/INFO]: Using standard Java JCE cipher.
[15:15:13] [main/INFO]: Using standard Java compressor.
[15:15:13] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:cc856ed:552
[15:15:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
[15:15:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
[15:15:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
[15:15:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
[15:15:13] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
[15:15:13] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
[15:15:13] [main/INFO]: [MoeFilter] Using MoeFilter API
[15:15:13] [main/INFO]: Loaded plugin MoeFilter version 0.1.4 by CatMoe
[15:15:13] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/WARN]: Forced host server pvp is not defined
[15:15:13] [main/INFO]: _____ ______   ________  _______   ________ ___  ___   _________  _______   ________     
[15:15:13] [main/INFO]: |\   _ \  _   \|\   __  \|\  ___ \ |\  _____\  \|\  \ |\___   ___\  ___ \ |\   __  \    
[15:15:13] [main/INFO]: \ \  \\__\ \  \ \  \|\  \ \   __/|\ \  \__/\ \  \ \  \|___ \  \_\ \   __/|\ \  \|\  \   
[15:15:13] [main/INFO]:  \ \  \|__| \  \ \  \\  \ \  \_|/_\ \   __\ \  \ \  \    \ \  \ \ \  \_|/_\ \   _  _\  
[15:15:13] [main/INFO]:   \ \  \    \ \  \ \  \\  \ \  \_|\ \ \  \_| \ \  \ \  \____\ \  \ \ \  \_|\ \ \  \  \ 
[15:15:13] [main/INFO]:    \ \__\    \ \__\ \_______\ \_______\ \__\   \ \__\ \_______\ \__\ \ \_______\ \__\ _\ 
[15:15:13] [main/INFO]:     \|__|     \|__|\|_______|\|_______|\|__|    \|__|\|_______|\|__|  \|_______|\|__|\|__|
[15:15:13] [main/INFO]:                                                                                           
[15:15:13] [main/INFO]: [MoeFilter] Detected Waterfall log4j logger. use it for main logger.
[15:15:13] [main/INFO]: [MoeFilter] LoggerManager are successfully loaded.
[15:15:13] [main/WARN]: [MoeFilter] [Pipeline] Starting inject MoeFilter Pipeline...
[15:15:13] [main/WARN]: [MoeFilter] [Pipeline] Pipeline inject successfully.
[15:15:13] [main/INFO]: Enabled plugin MoeFilter version 0.1.4 by CatMoe
[15:15:13] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.20-R0.2-SNAPSHOT:cc856ed:552 by WaterfallMC
[15:15:13] [MoeFilter Pool Thread #1/INFO]: [MoeFilter] [ProxyFetch] Starting Async proxy fetcher. (39 Threads)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: java.lang.reflect.InvocationTargetException
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at catmoe.fallencrystal.translation.event.EventManager.callEvent(EventManager.kt:85)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at catmoe.fallencrystal.moefilter.util.plugin.AsyncLoader.registerListener(AsyncLoader.kt:197)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at catmoe.fallencrystal.moefilter.util.plugin.AsyncLoader.load$lambda$2(AsyncLoader.kt:112)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: Caused by: java.lang.NoSuchMethodError: 'void net.md_5.bungee.protocol.packet.Kick.<init>(java.lang.String)'
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at catmoe.fallencrystal.moefilter.network.common.kick.FastDisconnect.getCacheReason(FastDisconnect.kt:118)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at catmoe.fallencrystal.moefilter.network.common.kick.FastDisconnect.initMessages(FastDisconnect.kt:99)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at catmoe.fallencrystal.moefilter.network.common.kick.FastDisconnect.reload(FastDisconnect.kt:86)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	at catmoe.fallencrystal.moefilter.common.config.ReloadConfig.reloadConfig(ReloadConfig.kt:80)
[15:15:13] [MoeFilter Pool Thread #0/ERROR]: 	... 11 more
[15:15:13] [Netty Boss IO Thread #0/INFO]: Listening on /0.0.0.0:25577
[15:15:13] [MoeFilter Pool Thread #42/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@53b8afea, id=43, owner=catmoe.fallencrystal.moefilter.MoeFilterBungee@6c302a1d, task=catmoe.fallencrystal.moefilter.common.counter.ConnectionStatistics$$Lambda$316/0x000002790137eaa0@17aa5a45, delay=0, period=50, running=true) encountered an exception
java.lang.NumberFormatException: For input string: "0,00"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
	at catmoe.fallencrystal.translation.utils.system.CPUMonitor.getRoundedCpuUsage(CPUMonitor.kt:58) ~[?:?]
	at catmoe.fallencrystal.moefilter.common.state.StateManager.tickProfile(StateManager.kt:133) ~[?:?]
	at catmoe.fallencrystal.moefilter.common.counter.ConnectionStatistics.schedule(ConnectionStatistics.kt:52) ~[?:?]
	at catmoe.fallencrystal.moefilter.common.counter.ConnectionStatistics._init_$lambda$0(ConnectionStatistics.kt:36) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:cc856ed:552]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

```

**Comment by FallenCrystal** [comment]
im going to look at this issue now. 1.20.2 broke too many things.

**Comment by FallenCrystal** [comment]
later versions of BungeeCord require packets to be written to a BaseComponent and the direct write string method has been removed. make it need, for each kick you need to convert the component to a string.

> that mean u will get more worse performance :(

this doesn't have much of an impact on our virtual servers. However, we recommend not turning off the virtual server feature. It is on by default.
~~I'll push a patch later.~~

**Comment by FallenCrystal** [comment]
I was annoyed. this basically breaks messaging utility v2 and a whole bunch of other stuff.
considering backward compatibility issues. i wont be updating these just yet. (i will update it later. but not now.) If needed. please use an older version of waterfall. im sorry.
if u need, contact me on discord `FallenCrystal#6883`. or look for other alternatives. for example, what i mentioned earlier.

**Comment by FallenCrystal** [comment]
Follow more developments and fixes for this issue [here](https://github.com/CatMoe/MoeFilter/tree/solve-issue-75).

**Comment by FallenCrystal** [comment]
A temp file to fix that. there may be other issues. Use with caution in a production environment.
[MoeFilter.zip](https://github.com/CatMoe/MoeFilter/files/13298271/MoeFilter.zip)

**Comment by FallenCrystal** [comment]
Wait for release.

**Comment by FallenCrystal** [comment]
Ah. to make sure we really don't have a problem. we may need to test the full version of the minecraft client and two different versions of Bungeecord.

**Comment by FallenCrystal** [comment]
hey, @shaqupl . In case you don't know that we have released a release with this patch. If you continue to consider using this plugin, please download it [here](https://github.com/CatMoe/MoeFilter/releases/tag/0.1.4-Hotfix1).
