### ISSUE TITLE
java.lang.IllegalArugmentException: Cannot convert mixed JsonArray to Tag

### ISSUE THREAD

**Issue by FallenCrystal** [CatMoe/MoeFilter#98]
```
 java.lang.IllegalArgumentException: Cannot convert mixed JsonArray to Tag
       at catmoe.fallencrystal.moefilter.network.limbo.compat.message.NbtMessage$Companion.fromJson(NbtMessage.kt:108)
       at catmoe.fallencrystal.moefilter.network.limbo.compat.message.NbtMessage$Companion.fromJson(NbtMessage.kt:75)
       at catmoe.fallencrystal.moefilter.network.limbo.compat.message.NbtMessage$Companion.create(NbtMessage.kt:46)
       at catmoe.fallencrystal.moefilter.network.limbo.packet.s2c.PacketDisconnect.setMessage(PacketDisconnect.kt:32)
       at catmoe.fallencrystal.moefilter.network.common.kick.FastDisconnect.getCacheReason(FastDisconnect.kt:111)
       at catmoe.fallencrystal.moefilter.network.common.kick.FastDisconnect.initMessages(FastDisconnect.kt:99)
       at catmoe.fallencrystal.moefilter.network.common.kick.FastDisconnect.reload(FastDisconnect.kt:87)
       at catmoe.fallencrystal.moefilter.common.config.ReloadConfig.reloadConfig(ReloadConfig.kt:82)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
       at catmoe.fallencrystal.translation.event.EventManager.callEvent(EventManager.kt:90)
       at catmoe.fallencrystal.moefilter.util.plugin.AsyncLoader.registerListener(AsyncLoader.kt:196)
       at catmoe.fallencrystal.moefilter.util.plugin.AsyncLoader.load$lambda$2(AsyncLoader.kt:117)
       at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by FallenCrystal** [comment]
i think they fuck up
